#!/bin/bash

htop
moc
vim
kile
sl
lock
klavaro
pandoc
wxmaxima
irssi
byobu


#read -p 'Voulez vous telecharger vim ? (yes/no)' validation
#if [  = yes  ] then
#sudo apt install vim
#fi
#read -p 'Voulez vous telecharger vim ? (yes/no)' validation
#if [  = yes  ] then
#sudo apt install vim
#fi
#read -p 'Voulez vous telecharger vim ? (yes/no)' validation
#if [  = yes  ] then
#sudo apt install vim
#fi
